### ISSUE TITLE
Add order of columns written

### ISSUE THREAD

**Issue by Brien45** [ybonnel/CsvEngine#6]
Hello,

I've problem with the order, that the colums are written : 
On the CSVEngine.class line 587 i see 
Collections.sort(columnsNames, new Comparator<String>()

But my problem is that the Alphabetical order don't do what i want, is it possible to add order in the @CsvFile class's like jcsv ?

**Comment by ybonnel** [comment]
Which version do you use? (last is 1.3.6)

To order columns, I use "order" parameter of @CsvColumn.

You can have a look to the test in order to see how to use it :
https://github.com/ybonnel/CsvEngine/blob/master/src/test/java/fr/ybonnel/csvengine/CsvEngineTest.java#L57

**Comment by Brien45** [comment]
Thank you, for your quick response
I'm using version 1.3.4, i've just change to 1.3.6 and with using "order" parameter like the junit test, 
It's work.
